version: '3.8'

services:
  tns.server:
    image: ${DOCKER_REGISTRY-}tnsserver
    build:
      context: .
      dockerfile: tns.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UserDb=Server=tns.db;Port=5432;Database=tnsDb;User Id=tnsUser;Password=Password123;
    depends_on:
      - tns.db
    ports:
      - "5000:80"
      - "5001:443"

  tns.db:
    image: postgres:17-alpine
    container_name: tns.db
    environment:
      POSTGRES_DB: tnsDb
      POSTGRES_USER: tnsUser
      POSTGRES_PASSWORD: Password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tnsUser -d tnsDb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: